# Generated by Django 6.0.5 on 2026-05-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_city_contact_contactphoto_countrycode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='mobile number'),
        ),
    ]
