# Generated by Django 6.0.5 on 2026-05-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_appuser_full_name_appuser_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gift_status',
            field=models.CharField(choices=[('PLANNED', 'Gift Planned'), ('PACKED', 'Gift Packed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered')], default='PLANNED', max_length=50),
        ),
    ]
